POST http://127.0.0.1:8000/auth/token/
content-type: application/json

{
    "username": "admin@accentiqa.com",
    "password": "admin"
}

###

GET http://13.201.33.169:8000/api/users/profile/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIwMDA1NDY4LCJpYXQiOjE3MTk5OTgyNjgsImp0aSI6ImNmZTczMWMwMzU3ODQ2ZGI4YjBmYmFjZmMyNzAyZWE1IiwidXNlcl9pZCI6MX0.2JUs_oOWsGK5LZ4o7HnuAfngxqh3dK9wUi9_UXymn2Q

### api for delete user
DELETE http://127.0.0.1:8000/api/users/usersProfile/17/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIwMDk2MTY3LCJpYXQiOjE3MjAwODg5NjcsImp0aSI6IjQxZDIzNGVlMmVkODQ3NjRhMmE5NGU2OGYzMzI4MDQyIiwidXNlcl9pZCI6MX0.OFAcvpOsfPM9d_81pcMFDyumgRg6qxEtzpDkdGMKGIs

###

POST http://127.0.0.1:8000/api/users/usersProfile/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5OTk1NzA1LCJpYXQiOjE3MTk5ODg1MDUsImp0aSI6IjFjYjY0ODc2MjI2MjQxNjI4NWU5OGZlNDkwMjljZWU5IiwidXNlcl9pZCI6MX0.VHmlAPVeQZeVGUt-3ng3vhq5MCCF4sarOytxwipPQqY

{
    "email":"manasa.gangumolu@aware247.com",
    "password":"Mr@vi777*9",
    "first_name":"G",
    "last_name":"Manasa",
    "phone_number":"9912277789",
    "is_mla":"1"
}


###

PATCH http://127.0.0.1:8000/api/users/usersProfile/1/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIwMDk2MTY3LCJpYXQiOjE3MjAwODg5NjcsImp0aSI6IjQxZDIzNGVlMmVkODQ3NjRhMmE5NGU2OGYzMzI4MDQyIiwidXNlcl9pZCI6MX0.OFAcvpOsfPM9d_81pcMFDyumgRg6qxEtzpDkdGMKGIs

{
    "email":"ngnaireddy@accentiqa.com",
    "first_name":"Naresh",
    "last_name":"reddy",
    "phone_number":"1345678931",
    "is_mla":"0",
    "gender":"male"

}


###

POST http://127.0.0.1:8000/api/users/pilgrims/
content-type: application/json
Authorization: Bearer   eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNDEwMTEwLCJpYXQiOjE3MjI0MDI5MTAsImp0aSI6ImQxMDIwZTY4NjQ4OTRiNjQ4YmQ2OGMxYzBlNDkyZGY0IiwidXNlcl9pZCI6MjF9.MH0TeRhrx4uMoGSrjy9v_rTJSxt-5QOFokpi34P6tg4

# [
#     {
#         "pilgrim_name": "gnr123",
#         "phone_number": "1232578931",
#         "aadhaar_number": "12348311213",
#         "age": "28",
#         "booked_datetime":"2024-06-26 07:31:08",
#         "is_master":"1"
#     },
#     {"pilgrim_count":"6"}

# ]

{
   "pilgrims":[
      {
         "booked_datetime":"2024-07-31",
         "seva":"VIP Break",
         "aadhaar_number":232323671023,
         "phone_number":1212121212,
         "age":56,
         "pilgrim_name":"TestUser1",
         "is_master":true
      }
   ],
   "pilgrim_count":1,
   "booked_datetime":"2024-07-31"
}



###
Patch http://127.0.0.1:8000/api/users/pilgrims/pilgrim_update/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzNTM2ODcyLCJpYXQiOjE3MjM1Mjk2NzIsImp0aSI6ImExNWM5ZGVmMzE5MTQ4NjBhZWRhNDI4NDRjMDQzZTRmIiwidXNlcl9pZCI6MjF9.pbQ7fIhx9XuzyTQdokSV8_KB2aG_1R4bJ_U2zPSahZc

[
  {
    "0": {
      "booked_datetime": "2024-08-17T00:00:00Z",
      "seva": "VIP Break",
      "aadhaar_number": 232323671023,
      "phone_number": 1212121212,
      "age": 34,
      "pilgrim_name": "TestUser1_edit_21",
      "pilgrim_id": 239,
      "created_datetime": "2024-08-13T05:20:19Z",
      "modified_datetime": "2024-08-13T05:24:58Z",
      "gender": null,
      "is_master": true,
      "user": 21,
      "editable": false,
      "clicked": true,
      "id": "5ee91a8b-ec21-4069-a413-0a65de9bb515"
    },
    "1": {
      "booked_datetime": "2024-08-17T00:00:00Z",
      "seva": "VIP Break",
      "aadhaar_number": 125200901823,
      "phone_number": 1212121212,
      "age": 34,
      "pilgrim_name": "TestUser2_edit",
      "pilgrim_id": 240,
      "created_datetime": "2024-08-13T05:20:19Z",
      "modified_datetime": "2024-08-13T05:22:13Z",
      "gender": null,
      "is_master": false,
      "user": 21,
      "editable": false,
      "clicked": true,
      "id": "9d3f06a4-de8f-4e45-a730-4f83da61f011"
    },
    "2": {
      "booked_datetime": "2024-08-17T00:00:00Z",
      "seva": "VIP Break",
      "aadhaar_number": 128911289034,
      "phone_number": 1212121212,
      "age": 34,
      "pilgrim_name": "TestUser3_edit",
      "pilgrim_id": 241,
      "created_datetime": "2024-08-13T05:20:19Z",
      "modified_datetime": "2024-08-13T05:20:19Z",
      "gender": null,
      "is_master": false,
      "user": 21,
      "editable": false,
      "clicked": true,
      "id": "ccd0ae7e-52c4-49de-935e-a1c72d60c174"
    },
    "pilgrim_count": 3
  }
]


### Api to get the pilgrim
GET http://127.0.0.1:8000/api/users/pilgrims/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNTg1NjMyLCJpYXQiOjE3MjI1Nzg0MzIsImp0aSI6ImZjYzM0ZGU2NTZmMDQ1ZjZiYzk1MWJjNTk4NWFhNjAwIiwidXNlcl9pZCI6MjF9.JDede0HjP2xL81rsHLRYAiOPin9XT5S1HmKawC4uHqU


### Api to delete the pilgrim
DELETE http://127.0.0.1:8000/api/users/pilgrims/193/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNDk2NzcwLCJpYXQiOjE3MjI0ODk1NzAsImp0aSI6ImQxOGM5NzJlMWUzZjQyM2RiZjkwODMxNGZlOWUwYzAwIiwidXNlcl9pZCI6MjF9.jmr17jC8ShGmlsEYH0vjWP77bSU3UzNZ_s7PGnNnDsQ



###

GET http://127.0.0.1:8000/api/users/pilgrimstats/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNDA5MDI1LCJpYXQiOjE3MjI0MDE4MjUsImp0aSI6IjM4MTJkZWU2MjE3ZjRlMmE4MjU0MzdmZWU2YmY1NmEzIiwidXNlcl9pZCI6MjF9.Wajc2kexyRZnLpnfjUfuDt7KWhZVBVfHbZkNh8xu0H0


### Api for Block the dates 

POST http://127.0.0.1:8000/api/users/blockdates/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzNTM2ODcyLCJpYXQiOjE3MjM1Mjk2NzIsImp0aSI6ImExNWM5ZGVmMzE5MTQ4NjBhZWRhNDI4NDRjMDQzZTRmIiwidXNlcl9pZCI6MjF9.pbQ7fIhx9XuzyTQdokSV8_KB2aG_1R4bJ_U2zPSahZc

#payload
{
  "dates": ["2024-08-15", "2024-08-16"]
}

###  Unblock dates

PATCH  http://127.0.0.1:8000/api/users/blockdates/unblock/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MjI4NDE4LCJpYXQiOjE3MTkyMjEyMTgsImp0aSI6IjZhYTY4ODI0OTM0OTQ1ZWY5M2ZkZGM2N2VlMzhjNzI1IiwidXNlcl9pZCI6MX0.LWs_oCfnKWRzGpcqn5svGjiE-jnKSy5odz-zDdU4EQI

#payload
{
  "dates": ["2024-08-15", "2024-08-16"]
}



### Api for Block the dates 

GET http://127.0.0.1:8000/api/users/blockdates/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzNTM2ODcyLCJpYXQiOjE3MjM1Mjk2NzIsImp0aSI6ImExNWM5ZGVmMzE5MTQ4NjBhZWRhNDI4NDRjMDQzZTRmIiwidXNlcl9pZCI6MjF9.pbQ7fIhx9XuzyTQdokSV8_KB2aG_1R4bJ_U2zPSahZc


###  possword reset
POST http://127.0.0.1:8000/api/users/usersProfile/1/reset_password/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIwMDg4NjYwLCJpYXQiOjE3MjAwODE0NjAsImp0aSI6IjI3YmE4NDk0OWVjMTRjODI5OGYzMTdiN2ExM2NiMmQ1IiwidXNlcl9pZCI6MX0.AZc7pBqfxMcQ1GOQ4g-m4Uh8DokQOFXI1w9M4cs264U

{
    "username":"Nareshg"
    "new_password":"Gnr@7167",
    "confirm_password":"Gnr@7167"
}

###
POST http://127.0.0.1:8000/api/users/vip-darshan-letter/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyNDEyMDg1LCJpYXQiOjE3MjI0MDQ4ODUsImp0aSI6IjlmNjE1Y2U2NzFiZTRlZDE5M2FjOTQ1Y2NlOTYwYTM3IiwidXNlcl9pZCI6MjF9.NLkfe1CzxNrgqRod7Rn2xiOa2ecgNlw0q6zKPHDgps4

{
        "pilgrims": [{"pilgrim_name":"Naresh","phone_number":1234567890,"aadhaar_number":123456789012,"age":22}],
        "accommodation_date":"2012-04-23",
        "darshan_date":"2012-04-23",
        "pilgrims_count":4
}