POST http://127.0.0.1:8000/auth/token/
content-type: application/json

{
    "email": "ngangireddy@accentiqa.com",
    "password": "ng2020agroup"
}

###

GET http://127.0.0.1:8000/api/users/profile/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4OTQ5NTc4LCJpYXQiOjE3MTg5NDIzNzgsImp0aSI6IjAwYTFjMGRmZjljZTQzYjI4M2UwODU4ODNlOGVhZmNjIiwidXNlcl9pZCI6MX0.oW6fytAyenWNcf3p7oGIadQ0ih4FhVBkWWhqiAH7kgQ

###

POST http://127.0.0.1:8000/api/users/usersProfile/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDcyMDY2LCJpYXQiOjE3MTk0NjQ4NjYsImp0aSI6Ijk5YWNmNzNmNzFiMzRkNTk4M2QxZTY1NWQ4ZWZmNDcyIiwidXNlcl9pZCI6MX0.SkPBsBKbFAMJ6mTY_q8IrBToeErbk_SZjcFgtUZHono

{
    "email":"manasa.gangumolu@aware247.com",
    "password":"Mr@vi777*9",
    "first_name":"G",
    "last_name":"Manasa",
    "phone_number":"9912277789",
    "is_mla":"1"
}


###

PUT http://127.0.0.1:8000/api/users/usersProfile/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4ODg3NzIxLCJpYXQiOjE3MTg4ODA1MjEsImp0aSI6ImRkZTQ2MGM0MmJlOTRjZTI5NDlkNTI4YmI0MjU5MGY3IiwidXNlcl9pZCI6MX0.C3NXmgHUnNQh3l44Gte0WbI_BylzcFjfw4z4rnLieUA

{
    "email":"ngnaireddy716777@gmail.com",
    "password":"ng2020agroup",
    "first_name":"Naresh",
    "last_name":"reddy",
    "phone_number":"1345678931",
    "is_mla":"0"

}


###

POST http://127.0.0.1:8000/api/users/pilgrims/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NjM1NTEzLCJpYXQiOjE3MTk1NDkxMTMsImp0aSI6IjlmNTc3ZDEwNjRiMjQ0ZTRhY2U2OWNkODdmYTczYzE4IiwidXNlcl9pZCI6MX0.g687lxNqbpsvEX39y4F63kAN6oih5UOoPOPqSFafFKg

[
    {
        "pilgrim_name": "gnr123",
        "phone_number": "1232578931",
        "aadhaar_number": "12348311213",
        "age": "28",
        "booked_datetime":"2024-06-26 07:31:08"

    }
]

###
Patch http://127.0.0.1:8000/api/users/pilgrims/pilgrim_update/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NjM1NTEzLCJpYXQiOjE3MTk1NDkxMTMsImp0aSI6IjlmNTc3ZDEwNjRiMjQ0ZTRhY2U2OWNkODdmYTczYzE4IiwidXNlcl9pZCI6MX0.g687lxNqbpsvEX39y4F63kAN6oih5UOoPOPqSFafFKg

[
    {        "pilgrim_id":"78",
            "pilgrim_name": "gnr123",
            "phone_number": "1232578931",
            "aadhaar_number": "12348311213",
            "age": "29",
            "booked_datetime":"2024-06-26 07:31:08"

    },
    {        "pilgrim_id":"79",
            "pilgrim_name": "manasa lakshmi",
            "phone_number": "1232578931",
            "aadhaar_number": "12121255",
            "age": "24"

    }
]


### Api to get the pilgrim
GET http://127.0.0.1:8000/api/users/pilgrims/?booked_datetime=2024-06-09
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NjM1NTEzLCJpYXQiOjE3MTk1NDkxMTMsImp0aSI6IjlmNTc3ZDEwNjRiMjQ0ZTRhY2U2OWNkODdmYTczYzE4IiwidXNlcl9pZCI6MX0.g687lxNqbpsvEX39y4F63kAN6oih5UOoPOPqSFafFKg




###

GET http://127.0.0.1:8000/api/users/pilgrimstats/?month=6&year=2024
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5NDcxODA5LCJpYXQiOjE3MTk0NjQ2MDksImp0aSI6IjYyNTBkMTE1YTNiNDRmOWRiNmVhMGZhZDFlODA5NWI1IiwidXNlcl9pZCI6MX0.9lcIixJ899CWD1WZiDioTzCP0q1xy6aMsgLKturkS7I


### Api for Block the dates 

POST http://127.0.0.1:8000/api/users/blockdates/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MjI4NDE4LCJpYXQiOjE3MTkyMjEyMTgsImp0aSI6IjZhYTY4ODI0OTM0OTQ1ZWY5M2ZkZGM2N2VlMzhjNzI1IiwidXNlcl9pZCI6MX0.LWs_oCfnKWRzGpcqn5svGjiE-jnKSy5odz-zDdU4EQI

#payload
{
  "dates": ["2024-08-15", "2024-08-16"]
}

###  Unblock dates

PATCH  http://127.0.0.1:8000/api/users/blockdates/unblock/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MjI4NDE4LCJpYXQiOjE3MTkyMjEyMTgsImp0aSI6IjZhYTY4ODI0OTM0OTQ1ZWY5M2ZkZGM2N2VlMzhjNzI1IiwidXNlcl9pZCI6MX0.LWs_oCfnKWRzGpcqn5svGjiE-jnKSy5odz-zDdU4EQI

#payload
{
  "dates": ["2024-08-15", "2024-08-16"]
}



### Api for Block the dates 

GET http://127.0.0.1:8000/api/users/blockdates/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE5MzE4NDYwLCJpYXQiOjE3MTkzMTEyNjAsImp0aSI6ImZlMGI4NzM5OGU4ZjRkNmU4OTg5ZjlkMjYzMWRjOGU0IiwidXNlcl9pZCI6MX0.WcVNcGWjM9mwBQyg9jju_UlsBGMCetRhprlPwb4ALpc
